# Generated by Django 3.0.5 on 2020-09-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='extra_KDM',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
