# Generated by Django 3.0.5 on 2020-09-10 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.PositiveIntegerField()),
                ('aadhar_card', models.PositiveIntegerField()),
                ('total_work', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('loss', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('paid', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='owner_profile_pics')),
                ('no_of_employees', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
