# Generated by Django 3.0.5 on 2020-09-10 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField(help_text='Mobile Number Without Country Code')),
                ('email', models.EmailField(max_length=254)),
                ('aadhar_card', models.PositiveIntegerField(help_text='Enter Aadhar Card UID Number')),
                ('address', models.TextField(max_length=300)),
                ('skills', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_date', models.DateTimeField(blank=True, null=True)),
                ('gold_toot', models.DecimalField(decimal_places=6, max_digits=15)),
                ('gold_toot_income', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('total_work', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('loss', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('paid', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='profile_pics')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.State')),
            ],
        ),
    ]
